import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../db/client", () => ({
  prisma: {
    prWebhookConfig: { findFirst: vi.fn(), findMany: vi.fn(), create: vi.fn() },
    prEvent: { create: vi.fn() },
  },
}));

vi.mock("../services/prCommenter", () => ({
  formatPrComment: vi.fn(() => "<!-- generated by reporank -->\n\n## RepoRank PR Impact\n\n-80 → 76"),
  commentSignature: vi.fn(() => "<!-- reporank-bot -->"),
}));

import request from "supertest";
import express from "express";
import prRoutes from "../routes/prs";
import { authMiddleware } from "../middleware/auth";
import { errorHandler } from "../middleware/errorHandler";

vi.mock("../middleware/auth", () => ({
  authMiddleware: (req: any, _res: any, next: any) => {
    req.userId = "user-1";
    next();
  },
  AuthRequest: class {},
}));

function makeApp() {
  const app = express();
  app.use(express.json());
  app.use("/api/v1/prs", authMiddleware as any, prRoutes);
  app.use(errorHandler);
  return app;
}

describe("POST /api/v1/prs/impact — handler integration", () => {
  it("returns a full impact report from the route handler", async () => {
    const res = await request(makeApp())
      .post("/api/v1/prs/impact")
      .send({
        currentScore: 80,
        changes: [
          { path: "src/a.ts", kind: "modified", content: "function f() { return 1; }", linesAdded: 1, linesRemoved: 0 },
        ],
      });
    expect(res.status).toBe(200);
    expect(res.body.data.predictedScore).toBeDefined();
    expect(res.body.data.totalDelta).toBeDefined();
    expect(res.body.data.vibeTrend).toBeDefined();
    expect(res.body.data.summary).toBeTruthy();
  });

  it("returns 400 when currentScore is missing", async () => {
    const res = await request(makeApp())
      .post("/api/v1/prs/impact")
      .send({ changes: [{ path: "a.ts", kind: "added" }] });
    expect(res.status).toBe(400);
    expect(res.body.code).toBe("VALIDATION_ERROR");
  });

  it("returns 400 when changes is empty", async () => {
    const res = await request(makeApp())
      .post("/api/v1/prs/impact")
      .send({ currentScore: 80, changes: [] });
    expect(res.status).toBe(400);
  });
});

describe("POST /api/v1/prs/recommendations — handler integration", () => {
  it("returns fix recommendations from a real impact analysis", async () => {
    const res = await request(makeApp())
      .post("/api/v1/prs/recommendations")
      .send({
        currentScore: 80,
        changes: [
          { path: "src/big.ts", kind: "added", content: "x".repeat(2000), linesAdded: 2000, linesRemoved: 0 },
        ],
      });
    expect(res.status).toBe(200);
    expect(res.body.data).toBeDefined();
    expect(Array.isArray(res.body.data) || typeof res.body.data === "object").toBe(true);
  });
});

describe("POST /api/v1/prs/comment — handler integration", () => {
  it("formats a markdown comment", async () => {
    const res = await request(makeApp())
      .post("/api/v1/prs/comment")
      .send({
        repoFullName: "owner/repo",
        prNumber: 42,
        currentScore: 80,
        changes: [
          { path: "src/a.ts", kind: "added", content: "function f() { return 1; }", linesAdded: 1, linesRemoved: 0 },
        ],
      });
    expect(res.status).toBe(200);
    expect(res.body.data.comment).toContain("reporank");
    expect(res.body.data.impact).toBeDefined();
  });
});
