import { CodebaseAnalysis, getRulesForMode, type RuleMode, type AgentRule } from "./rules";

const MODE_HEADERS: Record<RuleMode, string> = {
  minimal: "# AGENTS.md (Minimal)\n\nConcise rules that fit in context window.\n",
  standard: "# AGENTS.md\n\nAgent behavior guidelines generated by RepoRank.\n",
  comprehensive: "# AGENTS.md (Comprehensive)\n\nFull agent governance rules for this codebase.\n",
};

const SECTION_ORDER: string[] = ["agent-behavior", "security", "quality", "code-review", "education"];

const CATEGORY_LABELS: Record<string, string> = {
  "agent-behavior": "Agent Behavior",
  security: "Security",
  quality: "Code Quality",
  "code-review": "Code Review",
  education: "Education",
};

function renderRule(rule: AgentRule): string {
  const prefix = rule.severity === "must" ? "- **🔴 " : rule.severity === "should" ? "- **🟡 " : "- **🟢 ";
  return `${prefix}${rule.title}** — ${rule.description}`;
}

export function generateGuidelines(
  mode: RuleMode,
  analysis: CodebaseAnalysis,
  customRules?: AgentRule[],
): string {
  const rules = customRules || getRulesForMode(mode, analysis);
  const lines: string[] = [MODE_HEADERS[mode]];

  if (mode === "minimal") {
    lines.push("## Rules\n");
    for (const rule of rules) {
      lines.push(renderRule(rule));
    }
    lines.push("");
    if (analysis.vibeCodingScore > 30) {
      lines.push("> ⚠️ This codebase shows AI-generated code patterns. Verify all AI contributions carefully.");
    }
    return lines.join("\n");
  }

  // Standard and comprehensive get organized by category
  for (const cat of SECTION_ORDER) {
    const catRules = rules.filter(r => r.category === cat);
    if (catRules.length === 0) continue;
    lines.push(`## ${CATEGORY_LABELS[cat] || cat}\n`);
    for (const rule of catRules) {
      lines.push(renderRule(rule));
    }
    lines.push("");
  }

  // Comprehensive mode adds analysis summary
  if (mode === "comprehensive") {
    lines.push("## Codebase Context\n");
    lines.push(`- Files: ${analysis.fileCount}`);
    lines.push(`- Languages: ${analysis.languages.join(", ") || "Unknown"}`);
    lines.push(`- Vibe Coding Index: ${analysis.vibeCodingScore}/100`);
    lines.push(`- Security issues found: ${analysis.securityIssues}`);
    lines.push(`- Has CI: ${analysis.hasCI ? "Yes" : "No"}`);
    lines.push(`- Has tests: ${analysis.hasTests ? "Yes" : "No"}`);
    lines.push("");
  }

  return lines.join("\n");
}

export function estimateContextWindowFit(markdown: string, model: string = "claude"): {
  fits: boolean;
  tokenEstimate: number;
  maxTokens: number;
} {
  const tokenEstimate = Math.ceil(markdown.length / 4);
  const maxTokens = model === "claude" ? 200000 : 128000;
  return {
    fits: tokenEstimate < maxTokens * 0.15,
    tokenEstimate,
    maxTokens,
  };
}
