import { useEffect, useState } from "react";
import { useParams, Link } from "react-router";
import { api } from "../api/client";
import type { ScanResult } from "../api/client";
import ScoreGauge from "../components/ScoreGauge";
import ScoreBreakdown from "../components/ScoreBreakdown";
import VibeBreakdown from "../components/VibeBreakdown";
import SecuritySection from "../components/SecuritySection";

export default function ScanDetailPage() {
  const { id } = useParams<{ id: string }>();
  const [scan, setScan] = useState<ScanResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [timeseries, setTimeseries] = useState<any[]>([]);
  const report = scan?.result;
  const fixPacks = scan?.fixPacks;
  const trending = scan?.trending;
  const [copiedIdx, setCopiedIdx] = useState<number | null>(null);
  const [ghExportStatus, setGhExportStatus] = useState<string | null>(null);

  useEffect(() => {
    if (!id) return;
    const poll = setInterval(async () => {
      try {
        const s = await api.scans.get(id);
        setScan(s);
        if (s.status === "complete" || s.status === "error") clearInterval(poll);
      } catch (err: any) { setError(err.message); clearInterval(poll); }
    }, 2000);
    return () => clearInterval(poll);
  }, [id]);

  // Load timeseries data for trendline
  useEffect(() => {
    if (!id) return;
    fetch(`/api/v1/scans/${id}/timeseries`, {
      headers: { Authorization: `Bearer ${localStorage.getItem("reporank_token")}` },
    })
      .then((res) => res.json())
      .then((data) => setTimeseries(data.data?.timeseries || []))
      .catch(console.error);
  }, [id]);

  if (error) return <div className="min-h-screen bg-gray-950 flex items-center justify-center"><p className="text-red-400">{error}</p></div>;
  if (!scan) return <div className="min-h-screen bg-gray-950 flex items-center justify-center"><p className="text-gray-400">Loading scan...</p></div>;
  if (scan.status !== "complete" || !report) return (
    <div className="min-h-screen bg-gray-950 flex items-center justify-center">
      <div className="text-center">
        <p className="text-gray-400 text-lg mb-2">{scan.message || scan.status}</p>
        <div className="h-2 w-64 bg-gray-800 rounded-full overflow-hidden mx-auto">
          <div className="h-full bg-emerald-500 rounded-full transition-all duration-500" style={{ width: `${scan.progress}%` }} />
        </div>
        <p className="text-gray-500 text-sm mt-2">{scan.progress}%</p>
      </div>
    </div>
  );

  const copyToClipboard = async (text: string, idx: number) => {
    await navigator.clipboard.writeText(text);
    setCopiedIdx(idx);
    setTimeout(() => setCopiedIdx(null), 2000);
  };

  const exportToGitHub = async () => {
    if (!report) return;
    const token = prompt("Enter your GitHub personal access token (repo scope):");
    if (!token) return;

    setGhExportStatus("Creating issues...");
    let created = 0;
    const criticalWins = report.quickWins.filter(w => w.severity === "critical" || w.severity === "high");

    for (const win of criticalWins.slice(0, 5)) {
      try {
        const res = await fetch(`https://api.github.com/repos/${report.repoOwner}/${report.repoName}/issues`, {
          method: "POST",
          headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", Accept: "application/vnd.github.v3+json" },
          body: JSON.stringify({
            title: `[RepoRank] ${win.title}`,
            body: `## ${win.title}\n\n${win.description}\n\n**Severity:** ${win.severity}\n**Category:** ${win.category}\n**Effort:** ${win.effort}\n\n${win.action ? `**Action:** ${win.action}\n` : ""}\n${win.filePath ? `**File:** ${win.filePath}\n` : ""}\n---\n*Auto-generated by RepoRank. [Run a new scan](https://reporank.dev) for updated results.*`,
            labels: ["reporank", win.severity],
          }),
        });
        if (res.ok) created++;
        else break;
      } catch { break; }
    }
    setGhExportStatus(`Created ${created} issue(s)`);
    setTimeout(() => setGhExportStatus(null), 3000);
  };

  return (
    <div className="min-h-screen bg-gray-950">
      <header className="border-b border-gray-800/50">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <a href="/dashboard" className="text-lg font-bold">RepoRank</a>
          <span className="text-sm text-gray-400">{report.repoOwner}/{report.repoName}</span>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-6 py-8">
        {/* Score header */}
        <div className="flex flex-col md:flex-row gap-8 mb-8">
          <div className="relative flex items-center justify-center">
            <ScoreGauge score={report.overallScore} size={200} />
          </div>
          <div className="flex-1">
            <div className="flex items-center gap-4 mb-2">
              <span className="text-4xl font-bold">{report.overallScore}/100</span>
              <span className={`px-3 py-1 rounded-lg text-lg font-bold ${
                report.gradeCategory === "A" || report.gradeCategory === "A+" ? "bg-emerald-500/20 text-emerald-400" :
                report.gradeCategory === "B" || report.gradeCategory === "B+" ? "bg-blue-500/20 text-blue-400" :
                report.gradeCategory === "C" ? "bg-yellow-500/20 text-yellow-400" :
                "bg-red-500/20 text-red-400"}`}>{report.gradeCategory}</span>
              <span className="text-sm text-gray-500">{report.maturityLevel}</span>
            </div>
            <p className="text-gray-400 text-sm mb-4">{report.summary}</p>
            <div className="flex gap-4 text-sm text-gray-500">
              <span>📁 {report.architecture.fileCount} files</span>
              <span>⭐ {report.starsCount} stars</span>
              <span>🔀 {report.forksCount} forks</span>
              {trending && (
                <span className={trending.direction === "up" ? "text-emerald-400" : trending.direction === "down" ? "text-red-400" : "text-gray-500"}>
                  {trending.direction === "up" ? "▲" : trending.direction === "down" ? "▼" : "◆"} {trending.delta > 0 ? "+" : ""}{trending.delta} from previous scan
                </span>
              )}
            </div>
            <div className="flex gap-2 mt-4">
              <button onClick={() => window.print()}
                className="text-xs bg-gray-800 hover:bg-gray-700 text-gray-300 px-3 py-1.5 rounded-lg transition-colors">🖨️ Print Report</button>
              <button onClick={exportToGitHub}
                className="text-xs bg-gray-800 hover:bg-gray-700 text-gray-300 px-3 py-1.5 rounded-lg transition-colors"
                disabled={ghExportStatus !== null}>
                {ghExportStatus || "🐙 Export Issues"}
              </button>
              {trending?.previousScanId && (
                <Link to={`/compare/${trending.previousScanId}/${id}`} className="text-xs bg-gray-800 hover:bg-gray-700 text-gray-300 px-3 py-1.5 rounded-lg transition-colors">📊 Compare</Link>
              )}
            </div>
          </div>
        </div>

        {/* Health Trendline */}
        {timeseries.length > 1 && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800 mb-8">
            <h3 className="text-lg font-semibold mb-4">📈 Health Trendline</h3>
            <div className="flex items-end justify-between gap-2 h-40 bg-gray-800/30 p-4 rounded-lg">
              {timeseries.slice(-10).map((scan, i) => (
                <div key={i} className="flex-1 flex flex-col items-center gap-2">
                  <div className="relative w-full flex items-end justify-center h-32">
                    <div
                      className="w-full bg-gradient-to-t from-emerald-500 to-emerald-400 rounded-t opacity-80 hover:opacity-100 transition-opacity"
                      style={{ height: `${(scan.overallScore / 100) * 100}%` }}
                    />
                  </div>
                  <div className="text-xs text-gray-500 text-center">
                    <p className="font-semibold text-gray-300">{scan.overallScore}</p>
                    <p className="text-xs">{new Date(scan.scannedAt).toLocaleDateString()}</p>
                  </div>
                </div>
              ))}
            </div>
            <div className="mt-4 text-xs text-gray-500">
              <p>Last 10 scans • Score range: {Math.min(...timeseries.map((s) => s.overallScore))}—{Math.max(...timeseries.map((s) => s.overallScore))}</p>
            </div>
          </div>
        )}
        {scan.clawFindings?.unstick?.blockers?.length > 0 && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800 mb-8">
            <h3 className="text-lg font-semibold mb-4">🎯 What to Fix First — Priority Sequence</h3>
            <p className="text-sm text-gray-400 mb-4">
              {scan.clawFindings.unstick.summary}
            </p>

            {/* Top 3 summary cards */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
              <div className="bg-red-500/10 border border-red-500/20 rounded-lg p-4">
                <p className="text-xs text-red-400 font-semibold uppercase mb-1">Top Priority</p>
                <p className="text-sm text-gray-300">{scan.clawFindings.unstick.topPriority}</p>
              </div>
              <div className="bg-emerald-500/10 border border-emerald-500/20 rounded-lg p-4">
                <p className="text-xs text-emerald-400 font-semibold uppercase mb-1">Quickest Win</p>
                <p className="text-sm text-gray-300">{scan.clawFindings.unstick.quickestWin}</p>
              </div>
              <div className="bg-orange-500/10 border border-orange-500/20 rounded-lg p-4">
                <p className="text-xs text-orange-400 font-semibold uppercase mb-1">Biggest Risk</p>
                <p className="text-sm text-gray-300">{scan.clawFindings.unstick.biggestRisk}</p>
              </div>
            </div>

            {/* Full sequence */}
            <div className="space-y-3">
              {scan.clawFindings.unstick.blockers.map((b: any, i: number) => (
                <div key={i} className="flex gap-4 p-4 bg-gray-800/50 rounded-lg border-l-4 border-l-transparent hover:border-l-emerald-500/50 transition-colors">
                  <div className="flex flex-col items-center gap-1 min-w-[40px]">
                    <span className={`text-lg ${b.priority === 1 ? "text-red-400" : b.priority === 2 ? "text-orange-400" : b.priority === 3 ? "text-yellow-400" : "text-gray-500"}`}>
                      {b.priority === 1 ? "🔴" : b.priority === 2 ? "⚠️" : b.priority === 3 ? "🔶" : "💡"}
                    </span>
                    <span className="text-xs text-gray-600">P{b.priority}</span>
                  </div>
                  <div className="flex-1">
                    <div className="flex items-start justify-between gap-2">
                      <h4 className="font-medium text-sm">{b.title}</h4>
                      <span className={`text-xs px-2 py-0.5 rounded font-medium shrink-0 ${
                        b.effort === "minutes" ? "bg-emerald-500/20 text-emerald-400" :
                        b.effort === "hours" ? "bg-blue-500/20 text-blue-400" :
                        b.effort === "days" ? "bg-yellow-500/20 text-yellow-400" :
                        "bg-red-500/20 text-red-400"}`}>{b.effort}</span>
                    </div>
                    <div className="mt-2 grid grid-cols-2 gap-4 text-xs">
                      <div>
                        <p className="text-red-400 font-medium mb-0.5">If ignored:</p>
                        <p className="text-gray-500">{b.impact}</p>
                      </div>
                      <div>
                        <p className="text-emerald-400 font-medium mb-0.5">When fixed:</p>
                        <p className="text-gray-500">{b.payoff}</p>
                      </div>
                    </div>
                    {b.file && <p className="text-xs text-gray-600 mt-2 font-mono">{b.file}</p>}
                    {b.dependsOn?.length > 0 && (
                      <p className="text-xs text-gray-600 mt-1">Depends on: {b.dependsOn.join(", ")}</p>
                    )}
                    {b.unlocks?.length > 0 && (
                      <p className="text-xs text-emerald-500/70 mt-1">Unlocks: {b.unlocks.join(", ")}</p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Invisible Bugs — patterns senior devs miss */}
        {scan.clawFindings?.invisible?.findings?.length > 0 && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800 mb-8">
            <h3 className="text-lg font-semibold mb-4 text-red-400">👻 Invisible Bugs — Even Senior Devs Miss These</h3>
            <p className="text-sm text-gray-400 mb-4">
              {scan.clawFindings.invisible.summary}
            </p>
            <div className="space-y-3">
              {scan.clawFindings.invisible.findings.slice(0, 10).map((b: any, i: number) => (
                <div key={i} className={`flex gap-4 p-4 rounded-lg border-l-4 ${
                  b.severity === "critical" ? "bg-red-500/5 border-l-red-500" :
                  b.severity === "high" ? "bg-orange-500/5 border-l-orange-500" :
                  "bg-yellow-500/5 border-l-yellow-500"}`}>
                  <div className="flex flex-col items-center gap-1 min-w-[50px]">
                    <span className={`text-xs font-bold ${
                      b.confidence >= 80 ? "text-emerald-400" : b.confidence >= 60 ? "text-yellow-400" : "text-gray-500"}`}>
                      {b.confidence}%
                    </span>
                    <span className="text-[10px] text-gray-600">conf</span>
                    <span className={`text-xs px-1.5 py-0.5 rounded font-medium ${
                      b.severity === "critical" ? "bg-red-500/20 text-red-400" :
                      b.severity === "high" ? "bg-orange-500/20 text-orange-400" :
                      "bg-yellow-500/20 text-yellow-400"}`}>{b.severity[0].toUpperCase()}</span>
                  </div>
                  <div className="flex-1">
                    <p className="text-sm font-medium">{b.detail}</p>
                    <p className="text-xs text-gray-500 mt-1 italic">{b.seniorNote}</p>
                    <div className="bg-gray-800/50 rounded p-2 mt-2">
                      <p className="text-xs text-red-400/70 font-medium mb-0.5">💥 How it breaks:</p>
                      <p className="text-xs text-gray-400">{b.reproductionScenario}</p>
                    </div>
                    <p className="text-xs text-gray-600 mt-1 font-mono">{b.file}{b.line ? `:${b.line}` : ""}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Dimension grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800">
            <h3 className="text-lg font-semibold mb-4">Score Breakdown</h3>
            <ScoreBreakdown dimensions={report.dimensionScores} />
          </div>
          <SecuritySection security={report.security} />
        </div>

        {/* Vibe + Architecture */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
          <VibeBreakdown vibe={report.vibe} />
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800">
            <h3 className="text-lg font-semibold mb-4">Architecture</h3>
            <div className="space-y-3">
              {[
                { label: "Coupling", score: report.architecture.couplingScore, color: "#f59e0b" },
                { label: "Complexity", score: report.architecture.score, color: "#f59e0b" },
                { label: "Deployment", score: report.deployment.score, color: "#06b6d4" },
                { label: "Documentation", score: report.documentation.score, color: "#ec4899" },
                { label: "License", score: report.license.score, color: "#14b8a6" },
              ].map(item => (
                <div key={item.label} className="flex items-center gap-3">
                  <span className="w-24 text-sm text-gray-400">{item.label}</span>
                  <div className="flex-1 h-2 bg-gray-800 rounded-full overflow-hidden">
                    <div className="h-full rounded-full" style={{ width: `${item.score}%`, backgroundColor: item.color }} />
                  </div>
                  <span className="w-8 text-right text-sm text-gray-300">{item.score}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Implementation Plan — THE KEY NEW SECTION */}
        {report.implementationPlan && report.implementationPlan.length > 0 && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800 mb-8">
            <h3 className="text-lg font-semibold mb-4 text-emerald-400">📋 Fix Plan — Step by Step</h3>
            <div className="space-y-4">
              {report.implementationPlan.map((step, i) => (
                <div key={i} className="bg-gray-800/50 rounded-lg p-4 border border-gray-700/50">
                  <div className="flex items-start justify-between mb-2">
                    <h4 className="font-medium text-white">{i + 1}. {step.title}</h4>
                    <button onClick={() => copyToClipboard(step.promptInstruction, i)}
                      className="text-xs text-emerald-400 hover:text-emerald-300 shrink-0 ml-4">
                      {copiedIdx === i ? "Copied!" : "Copy Prompt"}
                    </button>
                  </div>
                  <p className="text-sm text-gray-400 mb-2">{step.description}</p>
                  {step.targetFiles && step.targetFiles.length > 0 && (
                    <div className="flex flex-wrap gap-2 mb-2">
                      {step.targetFiles.map((f, j) => (
                        <span key={j} className="text-xs bg-gray-700 text-gray-300 px-2 py-1 rounded font-mono">{f}</span>
                      ))}
                    </div>
                  )}
                  <div className="bg-gray-950 rounded p-3 mt-2">
                    <pre className="text-xs text-gray-400 whitespace-pre-wrap font-mono leading-relaxed">{step.promptInstruction}</pre>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Fix Packs */}
        {fixPacks && fixPacks.length > 0 && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800 mb-8">
            <h3 className="text-lg font-semibold mb-4 text-blue-400">📦 Auto-Generated Fix Patches</h3>
            <div className="space-y-4">
              {fixPacks.map((fp, i) => (
                <div key={i} className="bg-gray-800/50 rounded-lg p-4 border border-gray-700/50">
                  <div className="flex items-start justify-between mb-2">
                    <div>
                      <span className="text-xs text-gray-500 font-mono">{fp.filePath}</span>
                      <h4 className="font-medium text-white">{fp.title}</h4>
                    </div>
                    <button onClick={() => copyToClipboard(fp.content || "", i + 100)}
                      className="text-xs text-blue-400 hover:text-blue-300 shrink-0 ml-4">
                      {copiedIdx === i + 100 ? "Copied!" : "Copy Patch"}
                    </button>
                  </div>
                  <p className="text-sm text-gray-400 mb-2">{fp.description}</p>
                  {fp.content && (
                    <pre className="bg-gray-950 rounded p-3 text-xs text-gray-300 font-mono whitespace-pre-wrap overflow-x-auto max-h-48">
                      {fp.content}
                    </pre>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Quick Wins with Action + FilePath */}
        {report.quickWins.length > 0 && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800 mb-8">
            <h3 className="text-lg font-semibold mb-4">⚡ Quick Wins</h3>
            <div className="space-y-3">
              {report.quickWins.map((w, i) => (
                <div key={i} className="flex items-start gap-3 p-3 bg-gray-800/50 rounded-lg">
                  <span className={`px-2 py-0.5 rounded text-xs font-medium border shrink-0 ${
                    w.severity === "critical" ? "bg-red-500/20 text-red-400 border-red-500/30" :
                    w.severity === "high" ? "bg-orange-500/20 text-orange-400 border-orange-500/30" :
                    w.severity === "medium" ? "bg-yellow-500/20 text-yellow-400 border-yellow-500/30" :
                    "bg-blue-500/20 text-blue-400 border-blue-500/30"}`}>{w.severity.toUpperCase()}</span>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium">{w.title}</p>
                    <p className="text-xs text-gray-500 mt-1">{w.description}</p>
                    {w.action && <p className="text-xs text-emerald-400 mt-1 font-mono">{w.action}</p>}
                    <div className="flex flex-wrap gap-2 mt-1 text-xs text-gray-600">
                      <span>Effort: {w.effort}</span>
                      <span>Category: {w.category}</span>
                      {w.filePath && <span className="font-mono">File: {w.filePath}</span>}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Roadmap */}
        {report.roadmap.length > 0 && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800 mb-8">
            <h3 className="text-lg font-semibold mb-4">🗺️ Build Roadmap</h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {["now", "next", "later"].map(phase => (
                <div key={phase}>
                  <h4 className={`text-sm font-semibold uppercase mb-3 ${
                    phase === "now" ? "text-red-400" : phase === "next" ? "text-yellow-400" : "text-gray-400"}`}>{phase}</h4>
                  <div className="space-y-2">
                    {report.roadmap.filter(r => r.phase === phase).map((r, i) => (
                      <div key={i} className="bg-gray-800/50 rounded-lg p-3">
                        <p className="text-sm">{r.task}</p>
                        <p className="text-xs text-gray-500 mt-1">{r.category} · {r.effort}</p>
                      </div>
                    ))}
                    {report.roadmap.filter(r => r.phase === phase).length === 0 && (
                      <p className="text-xs text-gray-600 italic">No items</p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Senior Dev: Tech Debt Ratio */}
        {scan.clawFindings?.novel?.seniorDev?.debtRatio && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800 mb-8">
            <h3 className="text-lg font-semibold mb-4">📊 Tech Debt Ratio</h3>
            <p className="text-sm text-gray-400 mb-4">
              How long it would take to fix all identified issues vs. the original build time.
            </p>
            <div className="grid grid-cols-3 gap-4 mb-4">
              <div className="bg-gray-800/50 rounded-lg p-4 text-center">
                <p className="text-xs text-gray-500 mb-1">Fixable Issues</p>
                <p className="text-2xl font-bold">{scan.clawFindings.novel.seniorDev.debtRatio.fixableIssues}</p>
              </div>
              <div className="bg-gray-800/50 rounded-lg p-4 text-center">
                <p className="text-xs text-gray-500 mb-1">Est. Fix Time</p>
                <p className="text-2xl font-bold">{scan.clawFindings.novel.seniorDev.debtRatio.estimatedFixHours}h</p>
              </div>
              <div className="bg-gray-800/50 rounded-lg p-4 text-center">
                <p className="text-xs text-gray-500 mb-1">Debt Ratio</p>
                <p className={`text-2xl font-bold ${scan.clawFindings.novel.seniorDev.debtRatio.debtRatio > 30 ? "text-red-400" : scan.clawFindings.novel.seniorDev.debtRatio.debtRatio > 15 ? "text-yellow-400" : "text-emerald-400"}`}>
                  {scan.clawFindings.novel.seniorDev.debtRatio.debtRatio}%
                </p>
              </div>
            </div>
            <p className="text-sm text-gray-400">{scan.clawFindings.novel.seniorDev.debtRatio.summary}</p>
          </div>
        )}

        {/* Senior Dev: Risk Heatmap */}
        {scan.clawFindings?.novel?.seniorDev?.riskHeatmap?.items?.length > 0 && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800 mb-8">
            <h3 className="text-lg font-semibold mb-4 text-orange-400">🔥 Risk Heatmap</h3>
            <p className="text-sm text-gray-400 mb-4">Files with high complexity × high change risk. These are where bugs are most likely to appear.</p>
            <div className="space-y-2">
              {scan.clawFindings.novel.seniorDev.riskHeatmap.items.slice(0, 8).map((item: any, i: number) => (
                <div key={i} className="flex items-start gap-3 p-3 bg-gray-800/50 rounded-lg">
                  <span className={`text-sm font-bold ${item.riskScore > 30 ? "text-red-400" : item.riskScore > 20 ? "text-orange-400" : "text-yellow-400"}`}>{item.riskScore}</span>
                  <div className="flex-1">
                    <p className="text-sm font-mono">{item.file}</p>
                    <p className="text-xs text-gray-500 mt-1">{item.concern}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Senior Dev: Test Gaps */}
        {scan.clawFindings?.novel?.seniorDev?.testGaps?.gaps?.length > 0 && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800 mb-8">
            <h3 className="text-lg font-semibold mb-4 text-yellow-400">🧪 Test Coverage Gaps</h3>
            <p className="text-sm text-gray-400 mb-4">{scan.clawFindings.novel.seniorDev.testGaps.summary}</p>
            <div className="space-y-2">
              {scan.clawFindings.novel.seniorDev.testGaps.gaps.slice(0, 8).map((gap: any, i: number) => (
                <div key={i} className="flex items-start gap-3 p-3 bg-gray-800/50 rounded-lg">
                  <span className={`px-2 py-0.5 rounded text-xs font-medium ${gap.priority === "high" ? "bg-red-500/20 text-red-400" : "bg-yellow-500/20 text-yellow-400"}`}>{gap.priority.toUpperCase()}</span>
                  <div className="flex-1">
                    <p className="text-sm font-mono">{gap.sourceFile}</p>
                    <p className="text-xs text-gray-500 mt-1">Complexity: {gap.complexity}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Senior Dev: Bus Factor */}
        {scan.clawFindings?.novel?.seniorDev?.busFactor?.items?.length > 0 && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800 mb-8">
            <h3 className="text-lg font-semibold mb-4 text-red-400">👤 Bus Factor Analysis</h3>
            <p className="text-sm text-gray-400 mb-4">{scan.clawFindings.novel.seniorDev.busFactor.summary}</p>
            <div className="space-y-2">
              {scan.clawFindings.novel.seniorDev.busFactor.items.slice(0, 5).map((item: any, i: number) => (
                <div key={i} className="flex items-start gap-3 p-3 bg-gray-800/50 rounded-lg">
                  <span className={`px-2 py-0.5 rounded text-xs font-medium ${item.risk === "critical" ? "bg-red-500/20 text-red-400" : item.risk === "high" ? "bg-orange-500/20 text-orange-400" : "bg-yellow-500/20 text-yellow-400"}`}>{item.risk.toUpperCase()}</span>
                  <div className="flex-1">
                    <p className="text-sm font-mono">{item.file}</p>
                    <p className="text-xs text-gray-500 mt-1">{item.rationale}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Hallucinated features — now includes AI-code analysis first */}
        {scan.clawFindings?.novel?.aiCode?.findings?.length > 0 && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800 mb-8">
            <h3 className="text-lg font-semibold mb-4 text-red-400">🤖 AI-Generated Code Analysis</h3>
            <p className="text-sm text-gray-400 mb-4">
              Patterns unique to LLM-generated code. Spaghetti score: <span className="font-bold">{scan.clawFindings.novel.aiCode.spaghettiScore}/100</span>.
              Higher = more AI rewriting needed.
            </p>

            {/* Takeover points */}
            <div className="bg-gray-800/50 rounded-lg p-4 mb-4">
              <h4 className="text-sm font-semibold mb-2">🎯 Senior Dev Takeover Points</h4>
              <div className="space-y-1">
                {scan.clawFindings.novel.aiCode.takeOverPoints.map((point: string, i: number) => (
                  <p key={i} className="text-sm text-gray-300">{point}</p>
                ))}
              </div>
            </div>

            {/* Findings */}
            <div className="space-y-2">
              {scan.clawFindings.novel.aiCode.findings.slice(0, 12).map((f: any, i: number) => (
                <div key={i} className="flex items-start gap-3 p-3 bg-gray-800/50 rounded-lg">
                  <span className={`px-2 py-0.5 rounded text-xs font-medium shrink-0 ${
                    f.severity === "critical" ? "bg-red-500/20 text-red-400" :
                    f.severity === "high" ? "bg-orange-500/20 text-orange-400" :
                    f.severity === "medium" ? "bg-yellow-500/20 text-yellow-400" :
                    "bg-blue-500/20 text-blue-400"}`}>{f.severity.toUpperCase()}</span>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium">{f.detail}</p>
                    <p className="text-xs text-gray-500 mt-1 italic">{f.seniorNote}</p>
                    <p className="text-xs text-emerald-400 mt-1">→ {f.fixSuggestion}</p>
                    <p className="text-xs text-gray-600 mt-0.5 font-mono">{f.file}{f.line ? `:${f.line}` : ""}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
        {report.hallucinatedFeatures.length > 0 && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800 mb-8">
            <h3 className="text-lg font-semibold mb-4 text-orange-400">🌀 Hallucinated Features</h3>
            {report.hallucinatedFeatures.map((h, i) => (
              <p key={i} className="text-sm text-gray-400 mb-1">• {h}</p>
            ))}
          </div>
        )}

        {/* Structural smells */}
        {report.structuralSmells.length > 0 && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800 mb-8">
            <h3 className="text-lg font-semibold mb-4 text-yellow-400">👃 Structural Smells</h3>
            {report.structuralSmells.map((s, i) => (
              <p key={i} className="text-sm text-gray-400 mb-1">• {s}</p>
            ))}
          </div>
        )}

        {/* Bugs & Leaks */}
        {report.bugsAndLeaks.length > 0 && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800 mb-8">
            <h3 className="text-lg font-semibold mb-4 text-red-400">🐛 Bugs & Leaks</h3>
            {report.bugsAndLeaks.map((b, i) => (
              <p key={i} className="text-sm text-gray-400 mb-1 font-mono">• {b}</p>
            ))}
          </div>
        )}

        {/* Novel: Architecture Diagram */}
        {scan.clawFindings?.novel?.architectureDiagram?.mermaidCode && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800 mb-8">
            <h3 className="text-lg font-semibold mb-4">🏗️ Architecture Map</h3>
            <p className="text-sm text-gray-400 mb-4">
              {scan.clawFindings.novel.architectureDiagram.moduleCount} modules, {scan.clawFindings.novel.architectureDiagram.dependencyCount} inter-module dependencies.
              Copy the Mermaid code below into any Mermaid viewer (mermaid.live, GitHub markdown) to see the diagram.
            </p>
            <button onClick={() => navigator.clipboard.writeText(scan.clawFindings.novel.architectureDiagram.mermaidCode)}
              className="text-xs text-emerald-400 hover:text-emerald-300 mb-4 block">Copy Mermaid Code</button>
            <pre className="bg-gray-950 rounded p-3 text-xs text-gray-300 font-mono whitespace-pre-wrap overflow-x-auto max-h-64">
              {scan.clawFindings.novel.architectureDiagram.mermaidCode.slice(0, 2000)}
            </pre>
          </div>
        )}

        {/* Novel: Tech Debt Interest */}
        {scan.clawFindings?.novel?.techDebt?.items?.length > 0 && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800 mb-8">
            <h3 className="text-lg font-semibold mb-4">💰 Tech Debt Interest</h3>
            <p className="text-sm text-gray-400 mb-4">
              Estimated cost of leaving these issues unfixed. These are conservative estimates based on incident response patterns.
            </p>
            <div className="bg-gray-800/50 rounded-lg p-4 mb-4">
              <div className="flex items-center justify-between">
                <span className="text-gray-300 font-medium">Monthly Interest</span>
                <span className="text-xl font-bold text-orange-400">~{scan.clawFindings.novel.techDebt.totalMonthlyInterest}h</span>
              </div>
              <div className="flex items-center justify-between mt-2">
                <span className="text-gray-300 font-medium">Yearly Cost</span>
                <span className="text-xl font-bold text-red-400">${scan.clawFindings.novel.techDebt.totalYearlyCost?.toLocaleString?.() || scan.clawFindings.novel.techDebt.totalYearlyCost}/yr</span>
              </div>
            </div>
            <div className="space-y-2">
              {scan.clawFindings.novel.techDebt.items.slice(0, 5).map((item: any, i: number) => (
                <div key={i} className="flex items-start gap-3 p-3 bg-gray-800/50 rounded-lg">
                  <span className={`px-2 py-0.5 rounded text-xs font-medium ${item.severity === "critical" ? "bg-red-500/20 text-red-400" : item.severity === "high" ? "bg-orange-500/20 text-orange-400" : "bg-yellow-500/20 text-yellow-400"}`}>{item.severity.toUpperCase()}</span>
                  <div className="flex-1">
                    <p className="text-sm">{item.issue}</p>
                    <p className="text-xs text-gray-500 mt-1">{item.rationale}</p>
                    <p className="text-xs text-gray-600 mt-1">Fix: {item.fixEffort} · Cost: ~{item.interestHoursPerMonth}h/month · ${item.interestCostPerYear}/yr</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Novel: Dead Code Elimination Plan */}
        {scan.clawFindings?.novel?.deadCode?.steps?.length > 0 && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800 mb-8">
            <h3 className="text-lg font-semibold mb-4 text-yellow-400">🗑️ Dead Code Elimination Plan</h3>
            <p className="text-sm text-gray-400 mb-4">
              {scan.clawFindings.novel.deadCode.summary}
            </p>
            <div className="space-y-2">
              {scan.clawFindings.novel.deadCode.steps.map((step: any, i: number) => (
                <div key={i} className="flex items-start gap-3 p-3 bg-gray-800/50 rounded-lg">
                  <span className={`px-2 py-0.5 rounded text-xs font-medium ${step.riskLevel === "safe" ? "bg-emerald-500/20 text-emerald-400" : step.riskLevel === "moderate" ? "bg-yellow-500/20 text-yellow-400" : "bg-red-500/20 text-red-400"}`}>{step.riskLevel.toUpperCase()}</span>
                  <div className="flex-1">
                    <p className="text-sm font-mono">{step.symbol} in {step.file}</p>
                    <p className="text-xs text-gray-500 mt-1">{step.reason}</p>
                    <p className="text-xs text-gray-600 mt-1">Plan: {step.removalPlan}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Novel: Generated README */}
        {scan.clawFindings?.novel?.readme?.markdown && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800 mb-8">
            <h3 className="text-lg font-semibold mb-4 text-blue-400">📄 Generated README.md</h3>
            <p className="text-sm text-gray-400 mb-4">Auto-generated README with badges, architecture, and contribution guide.</p>
            <button onClick={() => navigator.clipboard.writeText(scan.clawFindings.novel.readme.markdown)}
              className="text-xs text-blue-400 hover:text-blue-300 mb-4 block">Copy README.md</button>
            <pre className="bg-gray-950 rounded p-3 text-xs text-gray-300 font-mono whitespace-pre-wrap overflow-x-auto max-h-96">
              {scan.clawFindings.novel.readme.markdown}
            </pre>
          </div>
        )}

        {scan.duration && (
          <p className="text-center text-sm text-gray-600">Scan completed in {scan.duration}s</p>
        )}
      </main>
    </div>
  );
}
