/**
 * Deploy module — Phase 5.
 *
 * Abstract provider interface, three concrete providers (Vercel, Docker, Fly),
 * and template generators for each.
 *
 * Usage (programmatic):
 *   import { generateTemplate, deploy } from "./deploy.js";
 *   generateTemplate("docker", "/path/to/project");
 *   await deploy({provider: "docker", projectPath: "/path/to/project"});
 *
 * Usage (CLI):
 *   reporank deploy generate docker my-project
 *   reporank deploy plan my-project
 */
import { existsSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

export type Provider = "vercel" | "docker" | "fly" | "static";

export const SUPPORTED_PROVIDERS: readonly Provider[] = ["vercel", "docker", "fly", "static"] as const;

export interface DeployOptions {
  provider: Provider;
  projectPath: string;
  /** Optional name override for the deployed service. */
  name?: string;
  /** Whether to actually call the provider CLI (vercel, docker, fly) or just generate files. */
  dryRun?: boolean;
  /** Overwrite existing files. Default false — skips with a warning. */
  force?: boolean;
  /** Additional provider-specific config. */
  config?: Record<string, string | number | boolean>;
}

export interface DeployResult {
  status: "ok" | "error" | "planned";
  provider: Provider;
  message: string;
  files?: string[];
  url?: string;
}

// ── Templates ─────────────────────────────────────────────────────────────────

function vercelJson(name: string): string {
  return JSON.stringify(
    {
      name,
      version: 2,
      builds: [{ src: "package.json", use: "@vercel/static-build" }],
      routes: [{ src: "/(.*)", "dest": "/$1" }],
      env: {
        VIBESERVE_API_KEY: "@vibeserve-api-key",
      },
    },
    null,
    2,
  );
}

function dockerfile(name: string): string {
  return `# Auto-generated by reporank deploy
FROM node:24-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:24-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
EXPOSE 3000
USER node
CMD ["node", "dist/server.js"]
LABEL org.opencontainers.image.title="${name}"
LABEL org.opencontainers.image.source="https://github.com/reporank/reporank"
`;
}

function dockerCompose(name: string): string {
  return `name: ${name}
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VIBESERVE_API_KEY=\${VIBESERVE_API_KEY}
    restart: unless-stopped
`;
}

function flyToml(name: string): string {
  return `# Auto-generated by reporank deploy
app = "${name}"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
`;
}

function staticConfig(): string {
  return JSON.stringify(
    {
      name: "mutly-static",
      version: 2,
      routes: [{ "src": "/(.*)", "dest": "/$1" }],
    },
    null,
    2,
  );
}

// ── Template generation ───────────────────────────────────────────────────────

export function generateTemplate(
  provider: Provider,
  projectPath: string,
  name?: string,
  options: { force?: boolean } = {},
): { written: string[]; skipped: string[] } {
  const root = resolve(projectPath);
  if (!existsSync(root)) {
    throw new Error(`Project path does not exist: ${root}`);
  }
  const inferred = name || root.split(/[\\/]/).pop() || "mutly-app";
  const written: string[] = [];
  const skipped: string[] = [];

  // Helper: write file, but skip if it already exists (unless force)
  const safeWrite = (p: string, contents: string): void => {
    if (existsSync(p) && !options.force) {
      skipped.push(p);
      return;
    }
    writeFileSync(p, contents, "utf-8");
    written.push(p);
  };

  if (provider === "vercel") {
    safeWrite(join(root, "vercel.json"), vercelJson(inferred));
  } else if (provider === "docker") {
    safeWrite(join(root, "Dockerfile"), dockerfile(inferred));
    safeWrite(join(root, "docker-compose.yml"), dockerCompose(inferred));
  } else if (provider === "fly") {
    safeWrite(join(root, "fly.toml"), flyToml(inferred));
    safeWrite(join(root, "Dockerfile"), dockerfile(inferred));
  } else if (provider === "static") {
    safeWrite(join(root, "vercel.json"), staticConfig());
  } else {
    throw new Error(`Unknown provider: ${provider}`);
  }

  // Also write a .dockerignore for Docker/Fly (always safe to write)
  if (provider === "docker" || provider === "fly") {
    safeWrite(
      join(root, ".dockerignore"),
      ["node_modules", "npm-debug.log", ".git", ".env", "coverage", "dist", ".DS_Store"].join("\n") + "\n",
    );
  }

  return { written, skipped };
}

// ── Plan (preview deploy) ─────────────────────────────────────────────────────

export interface DeployPlan extends DeployResult {
  projectType?: "node" | "python" | "unknown";
  projectName?: string;
  build_cmd?: string;
  output_dir?: string;
  base_image?: string;
  port?: number;
}

export function planDeploy(opts: DeployOptions): DeployPlan {
  const root = resolve(opts.projectPath);
  if (!existsSync(root)) {
    return { status: "error", provider: opts.provider, message: `Project path not found: ${root}` };
  }
  const inferred = opts.name || root.split(/[\\/]/).pop() || "mutly-app";

  // Detect project type
  const hasPackage = existsSync(join(root, "package.json"));
  const hasPyproject = existsSync(join(root, "pyproject.toml")) || existsSync(join(root, "requirements.txt"));
  const projectType = hasPackage ? "node" : hasPyproject ? "python" : "unknown";

  const plan: DeployPlan = {
    status: "planned",
    provider: opts.provider,
    message: `Plan for ${opts.provider} deployment of ${inferred} (${projectType})`,
    files: [],
    projectType,
    projectName: inferred,
  };

  if (opts.provider === "vercel" || opts.provider === "static") {
    plan.build_cmd = "npm run build";
    plan.output_dir = "dist";
  } else if (opts.provider === "docker" || opts.provider === "fly") {
    plan.base_image = hasPyproject ? "python:3.12-slim" : "node:24-alpine";
    plan.port = 3000;
  }

  return plan;
}

// ── Deploy (run provider CLI) ─────────────────────────────────────────────────

export async function deploy(opts: DeployOptions): Promise<DeployResult> {
  const plan = planDeploy(opts);
  if (plan.status === "error") return plan;

  // Always write the template files first
  const { written, skipped } = generateTemplate(opts.provider, opts.projectPath, opts.name, {
    force: opts.force,
  });

  const summary: string[] = [`Wrote ${written.length} file(s)`];
  if (skipped.length > 0) {
    summary.push(`skipped ${skipped.length} (use --force to overwrite)`);
  }

  if (opts.dryRun) {
    return {
      status: "planned",
      provider: opts.provider,
      message: `Dry-run: ${summary.join(", ")}`,
      files: written,
    };
  }

  return {
    status: "ok",
    provider: opts.provider,
    message: `${summary.join(", ")}. Run '${opts.provider}' CLI to actually deploy.`,
    files: written,
  };
}

// ── Read-back helpers (for dashboard) ─────────────────────────────────────────

export function readDeployStatus(projectPath: string): Record<string, unknown> {
  const root = resolve(projectPath);
  if (!existsSync(root)) return { error: "project not found" };
  return {
    project: root,
    hasDockerfile: existsSync(join(root, "Dockerfile")),
    hasDockerCompose: existsSync(join(root, "docker-compose.yml")),
    hasVercel: existsSync(join(root, "vercel.json")),
    hasFly: existsSync(join(root, "fly.toml")),
    hasPackage: existsSync(join(root, "package.json")),
    hasPyproject: existsSync(join(root, "pyproject.toml")),
  };
}
