/**
 * Phase 6 — instruction format translation, rule suggestions, feedback.
 *
 * Translates RepoRank/AGENTS.md-style guidelines into formats consumed by
 * other AI agent harnesses (Cursor, Aider, Claude Code, GitHub Copilot).
 *
 * Usage (programmatic):
 *   import { translateGuidelines, suggestRules, recordFeedback } from "./instructions.js";
 *   const cursorRules = translateGuidelines(guidelines, "cursor");
 *
 * Usage (CLI):
 *   reporank instructions translate <input> --to cursor -o .cursorrules
 *   reporank instructions suggest ./src
 *   reporank instructions feedback --up 1 --accepted
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

export type TargetFormat = "cursor" | "aider" | "claude" | "copilot" | "agents";

export const SUPPORTED_TARGET_FORMATS: readonly TargetFormat[] = [
  "cursor", "aider", "claude", "copilot", "agents",
] as const;

export interface GuidelineSection {
  id: string;
  title: string;
  severity: "must" | "should" | "may";
  body: string;
}

export interface ParsedGuidelines {
  source: TargetFormat | "raw";
  title: string;
  preamble: string;
  sections: GuidelineSection[];
}

/** Format-specific header comment. */
function formatHeader(format: TargetFormat): string {
  switch (format) {
    case "cursor":
      return `# Cursor rules — auto-generated from AGENTS.md\n# Edit the source AGENTS.md and re-run 'reporank instructions translate' instead.\n\n`;
    case "aider":
      return `# Aider conventions — auto-generated from AGENTS.md\n# Source: AGENTS.md — re-run 'reporank instructions translate' to refresh.\n\n`;
    case "claude":
      return `<!-- Claude Code memory — auto-generated from AGENTS.md -->\n<!-- Re-run 'reporank instructions translate' to refresh. -->\n\n`;
    case "copilot":
      return `# GitHub Copilot instructions — auto-generated from AGENTS.md\n# Path: .github/copilot-instructions.md\n\n`;
    case "agents":
      return `# AGENTS.md — generated by RepoRank\n\n`;
  }
}

function formatSection(format: TargetFormat, section: GuidelineSection): string {
  const tag = section.severity === "must" ? "MUST" : section.severity === "should" ? "SHOULD" : "MAY";
  switch (format) {
    case "cursor":
      return `## ${section.title}\n[${tag}] ${section.body.trim()}\n\n`;
    case "aider":
      return `## ${section.title}\n${tag}: ${section.body.trim()}\n\n`;
    case "claude":
      return `### ${section.title}\n[${tag}] ${section.body.trim()}\n\n`;
    case "copilot":
      return `### ${section.title}\n**${tag}** — ${section.body.trim()}\n\n`;
    case "agents":
      return `## ${section.title} (${tag})\n\n${section.body.trim()}\n\n`;
  }
}

// ── Translation ──────────────────────────────────────────────────────────────

export function translateGuidelines(guidelines: ParsedGuidelines, target: TargetFormat): string {
  let out = formatHeader(target);
  if (guidelines.preamble) {
    out += `${guidelines.preamble.trim()}\n\n`;
  }
  if (guidelines.title) {
    out += `# ${guidelines.title}\n\n`;
  }
  for (const s of guidelines.sections) {
    out += formatSection(target, s);
  }
  return out;
}

export function translateFile(inputPath: string, target: TargetFormat, outputPath?: string): {
  status: "ok" | "error";
  source_path: string;
  target: TargetFormat;
  output_path: string;
  bytes: number;
  error?: string;
} {
  const src = resolve(inputPath);
  if (!existsSync(src)) {
    return { status: "error", source_path: src, target, output_path: "", bytes: 0, error: "file not found" };
  }
  const raw = readFileSync(src, "utf-8");
  const parsed = parseGuidelines(raw, target);
  const translated = translateGuidelines(parsed, target);

  // Default to the input's directory (more predictable than CWD)
  const out = outputPath ? resolve(outputPath) : join(dirname(src), defaultFilename(target));
  try {
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, translated, "utf-8");
  } catch (e) {
    return { status: "error", source_path: src, target, output_path: out, bytes: 0, error: (e as Error).message };
  }
  return { status: "ok", source_path: src, target, output_path: out, bytes: translated.length };
}

function defaultFilename(target: TargetFormat): string {
  switch (target) {
    case "cursor": return ".cursorrules";
    case "aider": return "CONVENTIONS.md";
    case "claude": return "CLAUDE.md";
    case "copilot": return "copilot-instructions.md";
    case "agents": return "AGENTS.md";
  }
}

function defaultOutputPath(target: TargetFormat): string {
  return resolve(defaultFilename(target));
}

// ── Parser ──────────────────────────────────────────────────────────────────

const SEVERITY_TOKENS: Record<string, "must" | "should" | "may"> = {
  "MUST": "must", "MUST NOT": "must", "REQUIRED": "must", "SHALL": "must",
  "SHOULD": "should", "SHOULD NOT": "should", "RECOMMENDED": "should",
  "MAY": "may", "OPTIONAL": "may",
};

export function parseGuidelines(raw: string, _hint: TargetFormat | "raw" = "raw"): ParsedGuidelines {
  const lines = raw.split(/\r?\n/);
  const titleMatch = lines[0]?.match(/^#\s+(.+)$/);
  const title = titleMatch ? titleMatch[1].trim() : "";
  const sections: GuidelineSection[] = [];
  let preamble = "";
  let inPreamble = true;
  let current: GuidelineSection | null = null;

  for (let i = title ? 1 : 0; i < lines.length; i++) {
    const line = lines[i];
    const h2 = line.match(/^##\s+(.+?)(?:\s*\(?(must|should|may|MAY|SHOULD|MUST)\)?)?\s*$/i);
    if (h2) {
      inPreamble = false;
      if (current) sections.push(current);
      const sevToken = h2[2]?.toLowerCase();
      current = {
        id: h2[1].toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""),
        title: h2[1].trim(),
        severity: (sevToken === "must" || sevToken === "should" || sevToken === "may") ? sevToken : "should",
        body: "",
      };
      continue;
    }
    if (inPreamble) {
      if (line.trim().length > 0) preamble += line + "\n";
      continue;
    }
    if (current) {
      current.body += line + "\n";
    }
  }
  if (current) sections.push(current);

  // Detect severity from body if not set in heading
  for (const s of sections) {
    if (s.severity !== "should") continue;
    const firstLine = s.body.split("\n").find((l) => l.trim());
    if (firstLine) {
      const m = firstLine.match(/^\[?(MUST|SHOULD|MAY|REQUIRED|RECOMMENDED|OPTIONAL)(?:\s+NOT)?\]?/i);
      if (m) {
        const tok = m[1].toUpperCase();
        const mapped = SEVERITY_TOKENS[tok];
        if (mapped) s.severity = mapped;
      }
    }
  }

  return { source: "raw", title, preamble: preamble.trim(), sections };
}

// ── Rule suggestions (6.2) ──────────────────────────────────────────────────

export interface RuleSuggestion {
  id: string;
  title: string;
  severity: "must" | "should" | "may";
  rationale: string;
  evidence: string[];
  confidence: number;
}

const SUGGESTION_TEMPLATES: Array<{
  detect: (analysis: Record<string, unknown>) => boolean;
  build: (analysis: Record<string, unknown>) => RuleSuggestion;
}> = [
  {
    detect: (a) => (a["securityIssues"] as number) > 0,
    build: (a) => ({
      id: "no-secrets-in-code",
      title: "No secrets in code",
      severity: "must",
      rationale: `${a["securityIssues"]} potential secrets detected in the codebase.`,
      evidence: ["Secret-like patterns found in source files"],
      confidence: 0.95,
    }),
  },
  {
    detect: (a) => (a["aiGeneratedPatterns"] as number) > 5,
    build: (a) => ({
      id: "review-ai-generated-code",
      title: "Review AI-generated code carefully",
      severity: "should",
      rationale: `${a["aiGeneratedPatterns"]} AI-generated patterns detected — these often have subtle quality issues.`,
      evidence: ["Multiple files show patterns typical of LLM-generated code (over-eager comments, vague names, etc.)"],
      confidence: 0.8,
    }),
  },
  {
    detect: (a) => (a["hasTests"] as boolean) === false,
    build: () => ({
      id: "write-tests-for-core-logic",
      title: "Write tests for core logic",
      severity: "must",
      rationale: "No test files detected — critical functionality may be unverified.",
      evidence: ["No test framework configuration or test files found"],
      confidence: 0.9,
    }),
  },
  {
    detect: (a) => (a["hasLicense"] as boolean) === false,
    build: () => ({
      id: "include-license-file",
      title: "Include a LICENSE file",
      severity: "should",
      rationale: "No LICENSE file detected — unclear how the code may be used.",
      evidence: ["No LICENSE / LICENSE.md / LICENSE.txt found"],
      confidence: 0.85,
    }),
  },
  {
    detect: (a) => (a["errorHandlingGaps"] as number) > 0,
    build: (a) => ({
      id: "handle-async-errors",
      title: "Handle async errors with try/catch",
      severity: "must",
      rationale: `${a["errorHandlingGaps"]} async functions without error handling detected.`,
      evidence: ["Functions with `await` but no surrounding try/catch"],
      confidence: 0.85,
    }),
  },
];

export function suggestRules(analysis: Record<string, unknown>): RuleSuggestion[] {
  const out: RuleSuggestion[] = [];
  for (const tmpl of SUGGESTION_TEMPLATES) {
    if (tmpl.detect(analysis)) out.push(tmpl.build(analysis));
  }
  return out;
}

// ── Feedback loop (6.3) ──────────────────────────────────────────────────────

export interface RuleFeedback {
  ruleId: string;
  accepted: boolean;
  reason?: string;
  ts: number;
}

const FEEDBACK_PATH = resolve(".reporank-feedback.json");

export function recordFeedback(ruleId: string, accepted: boolean, reason?: string): RuleFeedback {
  const entry: RuleFeedback = { ruleId, accepted, reason, ts: Date.now() };
  let log: RuleFeedback[] = [];
  if (existsSync(FEEDBACK_PATH)) {
    try {
      log = JSON.parse(readFileSync(FEEDBACK_PATH, "utf-8"));
      if (!Array.isArray(log)) log = [];
    } catch {
      log = [];
    }
  }
  log.push(entry);
  try {
    mkdirSync(dirname(FEEDBACK_PATH), { recursive: true });
    writeFileSync(FEEDBACK_PATH, JSON.stringify(log, null, 2), "utf-8");
  } catch (e) {
    console.error("Could not persist feedback:", (e as Error).message);
  }
  return entry;
}

export function getFeedbackSummary(): { total: number; accepted: number; rejected: number; byRule: Record<string, { accepted: number; rejected: number }> } {
  if (!existsSync(FEEDBACK_PATH)) {
    return { total: 0, accepted: 0, rejected: 0, byRule: {} };
  }
  let log: RuleFeedback[] = [];
  try {
    log = JSON.parse(readFileSync(FEEDBACK_PATH, "utf-8"));
  } catch {
    return { total: 0, accepted: 0, rejected: 0, byRule: {} };
  }
  const byRule: Record<string, { accepted: number; rejected: number }> = {};
  let accepted = 0, rejected = 0;
  for (const f of log) {
    if (f.accepted) accepted++; else rejected++;
    const slot = byRule[f.ruleId] ?? { accepted: 0, rejected: 0 };
    if (f.accepted) slot.accepted++; else slot.rejected++;
    byRule[f.ruleId] = slot;
  }
  return { total: log.length, accepted, rejected, byRule };
}
